use Gestion_Parques_Naturales;
-- Inserciones de ejemplo para Entidad
INSERT INTO Entidad (nombre) VALUES 
('Ministerio del Medio Ambiente'),
('Parques Nacionales Naturales'),
('Corporaciones Autónomas Regionales'),
('Instituto de Investigación Ambiental'),
('Conservación Internacional'),
('Fundación Natura'),
('WWF Colombia'),
('EcoParques'),
('Conservación de Bosques'),
('Fundación Río Vivo'),
('Vida Verde'),
('Parques del Caribe'),
('Protección Andina'),
('Guardianes de la Selva'),
('Fauna Viva'),
('Amazonía Protegida'),
('Reserva Natural Colombia'),
('EcoAmazonía'),
('Bosques de Paz'),
('Sierra Nevada Conservación'),
('Páramo Andino'),
('Humedales Colombia'),
('Vida Silvestre'),
('Selva Viva'),
('Rescate Ambiental'),
('Protección Jaguar'),
('Oso Andino Conservación'),
('Aves de Colombia'),
('Recursos Naturales Colombia'),
('Bioparque Colombia'),
('Agua Viva'),
('Ríos Libres'),
('Montaña Verde'),
('Mar Caribe Conservación'),
('Reserva Coralina'),
('Red de Parques Comunitarios'),
('Mares Vivos'),
('Sabana Protegida'),
('Guardabosques Andinos'),
('Proyecto Arrecife'),
('Ecosistemas Andinos'),
('Patrimonio Natural'),
('Rescate Manglar'),
('Guardianes del Agua'),
('Alianza Verde'),
('Conservación Litoral'),
('Jardín Botánico Nacional'),
('Fundación Biodiversidad'),
('Fauna Viva Colombia'),
('Reserva Tropical');

-- Inserciones de ejemplo para Entidad
INSERT INTO Entidad (nombre) VALUES 
('Ministerio del Medio Ambiente'),
('Parques Nacionales Naturales'),
('Corporaciones Autónomas Regionales'),
('Instituto de Investigación Ambiental'),
('Conservación Internacional'),
('Fundación Natura'),
('WWF Colombia'),
('EcoParques'),
('Conservación de Bosques'),
('Fundación Río Vivo'),
('Vida Verde'),
('Parques del Caribe'),
('Protección Andina'),
('Guardianes de la Selva'),
('Fauna Viva'),
('Amazonía Protegida'),
('Reserva Natural Colombia'),
('EcoAmazonía'),
('Bosques de Paz'),
('Sierra Nevada Conservación'),
('Páramo Andino'),
('Humedales Colombia'),
('Vida Silvestre'),
('Selva Viva'),
('Rescate Ambiental'),
('Protección Jaguar'),
('Oso Andino Conservación'),
('Aves de Colombia'),
('Recursos Naturales Colombia'),
('Bioparque Colombia'),
('Agua Viva'),
('Ríos Libres'),
('Montaña Verde'),
('Mar Caribe Conservación'),
('Reserva Coralina'),
('Red de Parques Comunitarios'),
('Mares Vivos'),
('Sabana Protegida'),
('Guardabosques Andinos'),
('Proyecto Arrecife'),
('Ecosistemas Andinos'),
('Patrimonio Natural'),
('Rescate Manglar'),
('Guardianes del Agua'),
('Alianza Verde'),
('Conservación Litoral'),
('Jardín Botánico Nacional'),
('Fundación Biodiversidad'),
('Fauna Viva Colombia'),
('Reserva Tropical');


-- Inserciones para Departamento
INSERT INTO Departamento (nombre, capital, Entidad_id) VALUES 
('Antioquia', 'Medellín', 2),
('Cundinamarca', 'Bogotá', 3),
('Santander', 'Bucaramanga', 4),
('Valle del Cauca', 'Cali', 5),
('Amazonas', 'Leticia', 6),
('Chocó', 'Quibdó', 7),
('Boyacá', 'Tunja', 8),
('Atlántico', 'Barranquilla', 9),
('Córdoba', 'Montería', 10),
('La Guajira', 'Riohacha', 11),
('Huila', 'Neiva', 12),
('Magdalena', 'Santa Marta', 13),
('Nariño', 'Pasto', 14),
('Putumayo', 'Mocoa', 15),
('Tolima', 'Ibagué', 16),
('Cauca', 'Popayán', 17),
('Caquetá', 'Florencia', 18),
('Cesar', 'Valledupar', 19),
('Guaviare', 'San José del Guaviare', 20),
('Guainía', 'Inírida', 21),
('Meta', 'Villavicencio', 22),
('Vaupés', 'Mitú', 23),
('Vichada', 'Puerto Carreño', 24),
('Arauca', 'Arauca', 25),
('Quindío', 'Armenia', 26),
('Norte de Santander', 'Cúcuta', 27),
('San Andrés y Providencia', 'San Andrés', 28),
('Caldas', 'Manizales', 29),
('Risaralda', 'Pereira', 30),
('Bolívar', 'Cartagena', 31),
('Sucre', 'Sincelejo', 32),
('Casanare', 'Yopal', 33),
('Archipiélago de San Andrés', 'San Andrés', 34),
('Chocó', 'Quibdó', 35),
('Boyacá', 'Tunja', 36),
('Atlántico', 'Barranquilla', 37),
('Córdoba', 'Montería', 38),
('La Guajira', 'Riohacha', 39),
('Huila', 'Neiva', 40),
('Magdalena', 'Santa Marta', 41),
('Casanare', 'Yopal', 42),
('Arauca', 'Arauca', 43),
('Quindío', 'Armenia', 44),
('Norte de Santander', 'Cúcuta', 45),
('San Andrés y Providencia', 'San Andrés', 46),
('Caldas', 'Manizales', 47),
('Risaralda', 'Pereira', 48),
('Bolívar', 'Cartagena', 49),
('Sucre', 'Sincelejo', 50);

INSERT INTO Parque (nombre, fecha_declaracion) VALUES 
('Parque Nacional Natural Tayrona', '1964-04-24'),
('Parque Nacional Natural Sierra Nevada de Santa Marta', '1977-07-30'),
('Parque Nacional Natural Los Nevados', '1974-04-30'),
('Parque Nacional Natural El Cocuy', '1977-05-02'),
('Parque Nacional Natural Macuira', '1977-06-01'),
('Parque Nacional Natural Amacayacu', '1975-10-06'),
('Parque Nacional Natural Chingaza', '1977-05-06'),
('Parque Nacional Natural Farallones de Cali', '1968-01-01'),
('Parque Nacional Natural Las Orquídeas', '1974-03-03'),
('Parque Nacional Natural Utría', '1987-11-19'),
('Parque Nacional Natural Paramillo', '1977-08-08'),
('Parque Nacional Natural Gorgona', '1984-06-18'),
('Parque Nacional Natural Sumapaz', '1977-02-07'),
('Parque Nacional Natural Los Katíos', '1974-08-06'),
('Parque Nacional Natural Cahuinarí', '1987-08-26'),
('Parque Nacional Natural Old Providence McBean Lagoon', '1995-06-20'),
('Parque Nacional Natural Serranía de Chiribiquete', '1989-09-21'),
('Parque Nacional Natural Tinigua', '1989-10-22'),
('Parque Nacional Natural Puracé', '1961-04-22'),
('Parque Nacional Natural Tuparro', '1970-07-12'),
('Parque Nacional Natural Pisba', '1977-02-13'),
('Parque Nacional Natural Cordillera de los Picachos', '1977-09-28'),
('Parque Nacional Natural Los Flamencos', '1977-11-06'),
('Parque Nacional Natural Munchique', '1977-03-14'),
('Parque Nacional Natural La Paya', '1984-05-16'),
('Parque Nacional Natural Otún Quimbaya', '1996-06-10'),
('Parque Nacional Natural Isla de Salamanca', '1964-06-02'),
('Parque Nacional Natural Selva de Florencia', '1977-05-28'),
('Parque Nacional Natural Doña Juana Cascabel', '1989-10-04'),
('Parque Nacional Natural Galeras', '1985-06-17'),
('Parque Nacional Natural Sanquianga', '1977-11-13'),
('Parque Nacional Natural Corales del Rosario y San Bernardo', '1977-08-01'),
('Parque Nacional Natural Chorro El Indio', '1999-09-15'),
('Parque Nacional Natural Bahía Portete', '2003-08-06'),
('Parque Nacional Natural Serranía de Macuira', '1977-07-30'),
('Parque Nacional Natural Sierra de la Macarena', '1989-06-06'),
('Parque Nacional Natural Nukak', '1989-08-16'),
('Parque Nacional Natural Río Puré', '2002-10-05'),
('Parque Nacional Natural Acandí', '1987-09-30'),
('Parque Nacional Natural Churumbelos', '1999-06-22'),
('Parque Nacional Natural La Guajira', '1977-07-06'),
('Parque Nacional Natural Las Hermosas', '1977-05-17'),
('Parque Nacional Natural Bahía Málaga', '2010-02-08'),
('Parque Nacional Natural Guácharos', '1975-10-29'),
('Parque Nacional Natural Iguaque', '1977-02-13'),
('Parque Nacional Natural Puracé', '1977-09-29'),
('Parque Nacional Natural Yariguíes', '2005-08-08'),
('Parque Nacional Natural Uramba', '2010-10-19'),
('Parque Nacional Natural Los Colorados', '1977-02-19'),
('Parque Nacional Natural Serranía de los Motilones', '1990-07-05');


-- Inserciones para Departamento_Parque
INSERT INTO Departamento_Parque (Departamento_id, parque_id) VALUES 
(12, 1),
(13, 2),
(29, 3),
(7, 4),
(10, 5),
(5, 6),
(2, 7),
(4, 8),
(6, 9),
(35, 10),
(38, 11),
(4, 12),
(2, 13),
(6, 14),
(5, 15),
(28, 16),
(22, 17),
(22, 18),
(17, 19),
(24, 20),
(36, 21),
(22, 22),
(11, 23),
(17, 24),
(18, 25),
(48, 26),
(13, 27),
(29, 28),
(14, 29),
(14, 30),
(15, 31),
(31, 32),
(45, 33),
(11, 34),
(22, 35),
(20, 36),
(20, 37),
(21, 38),
(6, 39),
(14, 40),
(11, 41),
(17, 42),
(4, 43),
(18, 44),
(36, 45),
(17, 46),
(26, 47),
(30, 48),
(31, 49),
(41, 50);
